### ISSUE TITLE
Reducing Install Size a bit more

### ISSUE THREAD

**Issue by RichShumaker** [StevenHickson/RPiVideoLooper#7]
So I wanted to shrink the install a bit more from 3.7GB
So I started with Minibian - https://minibianpi.wordpress.com/
I started from scratch as the first version was unstable.
Below is the updated method I used.  At the end of creating this when I rebooted I now get a login BUT there is also video glitching like Green writing happening every 5 - 10 seconds.
I tested the hardware with another install and the hardware worked fine so the install I created has the glitching.
1. Use Minibian to image an SD memory chip
2. Install Raspi-config - `apt-get install raspi-config`
2a. I had to manually resize the first time - IF YOU DO NOT INSTALL THIS FIRST YOU WILL TOO
3. Use raspi-config to Expand the GPU to 128mb
4. Reboot Happens Automagically after you leave raspi-config
5. `apt-get update`
6. `apt-get upgrade`
7. Reboot
8. Create User `adduser pi` - Install all the Looper Software into the correct folders
9. Install Git - `apt-get install git`
10. Install OMX Player - `apt-get install omxplayer`
11. Install fbset `apt-get install fbset`
12. Move to the Pi Directory before you clone the respository
13. Clone Steven Hickenson's Directory `git clone https://github.com/StevenHickson/RPiVideoLooper
14. Install Steven Hickenson's Looper`
14a. Remove the tag from the Install Script #update-rc.d videoloop defaults - I used Filezilla to FTP and update the script - You could use VI but Nano is not installed
14b. `./install.sh`
15. Need to create` /home/pi/videos` and put videos into it
16. must install NTFS as that is what is used for the USB apt-get install ntfs-3g
17. changing `autostart.sh` to 755 as I could not get it to start when I tried as a stand alone file(I think the error is because I did not have a video folder) - ./autostart.sh: line 6: Starting: command not found Here is the code at line 6 service videoloop start
18. NEED TO update everything again
18a. `apt-get update`
18b. `apt-get upgrade`
19. Reboot
20. installed rpi-update `apt-get install rpi-update`
21. `rpi-update`
22. Copied fstab from the original looper image `/dev/sda1 /media/USB ntfs-3g defaults,noatime,nodiratime 0 0`

**Comment by stucksubstitute** [comment]
Minibian sounds interesting. Yes, creating a pi user sounds like a good idea. Also I suspect you might have to install USB drivers, as those are probably not included in Minibian.

**Comment by RichShumaker** [comment]
Thanks @stucksubstitute, I am in a world of hurt now as things were looking great then they took a turn for the worse after a bit.  So I am going to restart from scratch and try to rebuild slightly differently.  When I built it the first time as I found a problem I would fix it.  Now that I have fixed a bunch of issues and see a better way to build it(cough cough - Pi User sooner), I will be trying that.  Once I get to the end I will look for issues and fix any new issues.  Probably have a third go at it.

**Comment by RichShumaker** [comment]
I have everything but USB working so I created a disk image to see how BIG or small it would be.  Since it was a 2GB chip the image is 2GB but the zip file is 1.14GB so that is about 1/3 the original size of the videoloop.  Still have the blank screen showing up at the command line and no USB as I said.

**Comment by RichShumaker** [comment]
USB worked once I copied the fstab line from the original image file for the USB.
Instructions above are updated.
Here is the image file location -  https://drive.google.com/file/d/0B2w97gVYBA8wYWNxQm1pVUFYSG8/view?usp=sharing
From 3.7gb to just under 1gb compressed, WooHoo.
It will fit easily on a 2GB card and I think everything works from the original.
U: root P: Raspberry - Default for Minibian
Also U: pi P: Raspberry - Default created in Minibian based on Raspbian Base install and Looper Install

**Comment by stucksubstitute** [comment]
I'm now testing setting up https://github.com/adafruit/pi_video_looper which seems to run well on Jessie Lite. No hiccups, except I had to manually install omxplayer. Currently installing it on a 2GB SD card as a master.
